### ISSUE TITLE
[OS X]  Не запускается

### ISSUE THREAD

**Issue by yunoshev** [ReanGD/LearningEnglish#32]
``` bash
-> % python --version
Python 2.7.2
-> % python main.py 
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    run()
  File "main.py", line 53, in run
    os.chdir(os.path.dirname(__file__))
OSError: [Errno 2] No such file or directory: ''
```

**Comment by ReanGD** [comment]
Попробуйте "python ./main.py" или указать полный путь к main.py

**Comment by ReanGD** [comment]
И если не сложно, отпишитесь пожалуйста помогло ли?

**Comment by yunoshev** [comment]
Помогло. Но в целом логично же сделать, чтобы и так и так работало? Неужели в питоне это так сложно?

**Comment by ReanGD** [comment]
Это какая-то особенность интерпретатора под Linux и Mac OS. Попробую найти способ поправить.

**Comment by ReanGD** [comment]
Теперь запускается простым "python main.py" из текущей директории. Спасибо пользователю [elmit](https://github.com/elmit)

**Comment by ReanGD** [comment]
думаю можно закрывать.
