### ISSUE TITLE
Скрытие транскрипции

### ISSUE THREAD

**Issue by ReanGD** [ReanGD/LearningEnglish#39]
Добавить возможность в настройках запретить показ транскрипции

**Comment by elmit** [comment]
Я вообще предлагаю сделать транскрипцию необязательной. Опциональное поле в dict.json. Если в list-е два элемента, то считать что это слово и перевод, а если три, то слово-транскрипция-перевод

**Comment by ReanGD** [comment]
Реализовал, спасибо [alukardd](http://habrahabr.ru/users/alukardd) за идею и первоначальный вариант реализации.

И за что же вы так транскрипцию не любите? Ок создам сейчас отдельную задачку по загрузке словаря без колонки с транскрипцией.
