### ISSUE TITLE
Хочу версию под Android!

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#44]
Хочу версию под Android!

**Comment by ReanGD** [comment]
У меня нет никакого опыта разработки под мобильные платформы. Так что боюсь что версии не будет.
Если есть желание портировать - я всеми руками за.

**Comment by maxirk** [comment]
Попроситье на хабре в посте что ли :)

**Comment by ReanGD** [comment]
Надеюсь вы шутите. Среди нескольких десятков заинтересовавшихся вряд ли найдется профессиональный разработчик по Android, готовый бесплатно потратить около человека-месяца на проект и потом его постоянно поддерживать.

**Comment by maxirk** [comment]
Версию для Android можно и продавать. Вот только программку нужно
раскрутить - сделать все для обычных пользователей. Виндовую версию,
скомпилировать как обычную программу. Сделать промо-сайтик красивый. Просто
реально ваша идея - это гораздо лучше чем где-либо видел.

2012/10/10 Vladimir notifications@github.com

> Надеюсь вы шутите. Среди нескольких десятков заинтересовавшихся вряд ли
> найдется профессиональный разработчик по Android, готовый бесплатно
> потратить около человека-месяца на проект и потом его постоянно
> поддерживать.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ReanGD/LearningEnglish/issues/44#issuecomment-9274382.

## 

Богданов Максим Анатольевич маркетолог ЗАО "ТД "Энерпром"
+79140133371 max-irk www.enerprom.ru

**Comment by ReanGD** [comment]
Спасибо за лестное мнение.
Меня, к сожалению, не интересует раскрутка, продажи и т.п.
Это проект-хобби, которым я занимаюсь в редкие свободные минуты. Превращать его в работу - не хочу, работы и так слишком много в жизни.
Если у вас или у кого-то еще будет желание и возможность сделать на этом деньги - я не против.

**Comment by maxirk** [comment]
Кстати под Андроид я учу с помощью программы Wordoholic http://4pda.ru/forum/index.php?showtopic=157804
Посмотрите. Хотя там стандартная идеология - создаешь много словарей и потом они по расписанию выскакивают в строке уведомлений на повтор.

Поэтому вот бы здорово найти разработчика Android версии. В любом случае я думаю энтузиасты должны найтись. На хабре бы попросили сразу :) Ведь люди часто хотят и имеют навык программирования, но нет идеи программы, которую до них никто не реализовал. А у вас есть и до этого нигде не реализована.

**Comment by ReanGD** [comment]
Спасибо, посмотрю как время появится, я лично пользовался вот этим https://play.google.com/store/apps/details?id=com.wordsteps , но как-то не пошло у меня изучение на телефоне.
Насчет поиска энтузиастов - селяви, ну нет у меня сейчас времени, в лучшем случае пол часа в день десктопному проекту удается посвятить, а бегать уговаривать кого-то еще, совсем некогда, да и не тянет.

**Comment by ReanGD** [comment]
Итог: версия под мобильные OS не планируется, по крайней мере в обозримой перспективе.
