### ISSUE TITLE
Должна сворачиваться в трей.

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#46]
Когда запускаю, еще дополониетльно открывается пустое коммандное окно "main". Надо что бы хотя бы оно закрывалось или не открывалось.

Еще нужно что бы программа сворачивалась и висела в трее.

**Comment by ReanGD** [comment]
Насчет командного окна, я как понимаю вы работаете под windows, тогда у вас никакой проблемы нет - если не хотите запускать через консоль как написано в readme, то просто выберете "открыть с помощью" на файле main.py и укажите там путь к pythonW.exe (он находится в корне директории, куда вы установили python) + поставте галочку использовать эту программу по умолчанию.
Вот с Linux и OS X - пока не могу разобраться

**Comment by ReanGD** [comment]
Насчет трея - похоже что не существует кроссплатформенной реализации для tkinter. Если найду обязательно добавлю

**Comment by maxirk** [comment]
У меня проблема в этом 
См скрин: http://pic2net.ru/view/v/fdebc06c6cb7451aa68c7190e14515ec.jpg 
Нужно что бы данное окно не было видно - зачем оно мешается?

**Comment by maxirk** [comment]
Для Windows есть программы, которые умеют сворачивать по правому клику на "minimize" в трей.
Например
http://rbtray.sourceforge.net/ (простая) и http://www.4t-niagara.com/tray.html (новороченая)

**Comment by maks-a** [comment]
Что бы не появлялось окно консоли можно переименовать main.py в main.pyw, в Win такой файл будет помечен как Python File (no console).

**Comment by ReanGD** [comment]
Насчет трея - я не буду использовать решение жестко завязанное под одну платформу, да еще требующее установки дополнительного ПО, это не правильно. Лучше попробую поискать нечто более подходящее.

**Comment by ReanGD** [comment]
Насчет консоли - вы явно не хотите заморачиваться с pythonw. Тогда вам действительно подойдет вариант maks-a, правда я предлагаю не переименовывать main.py, что бы не иметь проблем с обновлением, а скачать вот [этот файл](http://narod.ru/disk/62580809001.40052ca9c994567fadf0edb337fdcde1/run.pyw.html) и запускать его.
Он ничего особенного не делает, просто запускает main.py и имеет нужное вам расширение.
PS: аккуратно не установите себе случайно yandex-bar скачивая файл )

**Comment by maxirk** [comment]
Спасибо, работает. По поводу сворачивания в трей ищите решение.
Помогите со словарем https://github.com/ReanGD/LearningEnglish/issues/55

**Comment by maxirk** [comment]
В принципе сворачивание в трей не нужно. Сейчас у меня по завершении упражнения, программа вообще исчезает (нет ни в трее ни в таскбаре). Как приходит время появляется окно для ввода.
