### ISSUE TITLE
Направление перевода

### ISSUE THREAD

**Issue by StasikBla** [ReanGD/LearningEnglish#48]
Можно ли добавить направление перевода ru-eng. Не нашёл в source, где изменить, только начал изучать язык. Уже пользуюсь, спасибо нужная вещь, не против переделаю сыну для изучения таблицы умножения, для этого и нужно узнать где направление изменить на постоянно: задание-> (2 Х 2) ответ ->(4)

**Comment by ReanGD** [comment]
>  не против переделаю сыну для изучения таблицы умножения

только за, если кому-то пригодиться код буду рад.

> Можно ли добавить направление перевода ru-eng

там присутствуют оба направления, они случайным образом выбираются в начале каждого урока, ничего специальным образом добавлять не нужно.
Если интересует место в коде, то в [lesson.py](https://github.com/ReanGD/LearningEnglish/blob/master/lesson.py) строка 38:
...
self.type_pr = random.choice([word.en_to_ru_write, word.ru_to_en_write])
...
если я правильно понял, то нужно не добавить, а все же убрать одно из направлений перевода, тогда можно поменять строку вот так:
...
self.type_pr = word.en_to_ru_write
...

**Comment by StasikBla** [comment]
Спасибо за понимание, да это та нужная мне строка.
