### ISSUE TITLE
Уйти от "накопительной" системы рейтинга к "текущей".

### ISSUE THREAD

**Issue by maks-a** [ReanGD/LearningEnglish#50]
Настоящая система рейтинга получается "накопительной", т.е. считаются ответы за все время существования карточки. Это замедляет "выучивание" сложных слов.

Например, есть слово которое очень сложно запоминается и поэтому пользователь вначале часто дает неправильный ответ, со временем ситуация улучшается и в какой-то момент пользователь начинает постоянно давать правильные ответы, но к этому моменту он уже набрал много неправильных ответов (например, 10), это значит, что для того что бы слово перешло в категорию "выучено" он должен на каждый неправильный ответ дать 10 правильных, т.е., в нашем случае, еще 100 раз ответить правильно.

Это долго, неюзабельно, раздражает пользователя.

Более подходящий алгоритм - помнить какое-то кол-во последних ответов (например, 10).
Схема "+10% за правильный ответ, -100% за неправильный" требует от пользователя дать подряд 10 правильных ответов для перевода слова в категорию "выучена" (вне зависимости от кол-ва ранее данных неправильных ответов). Можно чуть облегчить условия и отнимать за неправильный ответ 50%, 30% или 20% (сделать настраиваемой со значением по умолчанию -100%).
Схема "+10%/-20%", кажется, реализована в ABBYY Lingvo Tutor.

**Comment by ReanGD** [comment]
Потрясающе, спасибо большое. Долго думал над этой проблемой, но так и не нашел подходящего решения.
От "накопительной" системы статистики отказывать не буду полностью, оставлю ее в качестве информационной составляющей, но считать слово изученным действительно лучше предложенным методом - добавляя и уменьшая баллы за ответ.
Еще раз спасибо за идею.

**Comment by maks-a** [comment]
Различие в алгоритме расчета информационных процентов "выученности" и реальных может ввести пользователя в заблуждение.
В любом случае, спасибо Вам за реализацию, сделали то что я давно задумал, но руки не доходили, да и не по питону я...

**Comment by maxirk** [comment]
Ок. Напишите тут когда будет такая система.

**Comment by maxirk** [comment]
Все я тоже замучился одни и те же слова вводить.. Пока не буду использовать программу.

**Comment by maks-a** [comment]
предлагаю посмотреть мой вариант - он, конечно, сильно урезан, но зато с такой логикой отметки рейтинга как хотел - https://github.com/maks-a/LearnEnglishWords
за основу был взят вариант @ReanGD, спасибо большое ему за это!
я подумал, что проще самому разобраться с питоном и написать то что нужно мне, чем ждать пока кто-то это сделает для меня.
P.S. кстати, рабочий вариант получился за месяц в свободное от работы время, учитывая реверсинжинеринг варианта @ReanGD и изучение питона

**Comment by maxirk** [comment]
Ну раз код готов пусть ReanGD включает в свой родной проект?
А пока буду использовать версию от maks-a

**Comment by ReanGD** [comment]
maks-a, скачал - взглянул мельком, пока не могу полностью изучить. Интересно получилось, понравились некоторые интерфейсные решения, не возражаете, если я их частично скопирую? Попробую на выходных все же собраться с силами и взяться за свой проект, а то совсем забросил что-то (
Да и зря вы без тестов, сложнее потом будет.

**Comment by maks-a** [comment]
можете использовать все что хотите. писал без тестов, так как по ходу много раз все переделывал.

**Comment by ReanGD** [comment]
Готово, что делает думаю понятно по развернутому комментарию в самом начале.
