### ISSUE TITLE
После появления окна ввода слова сделать задержку в 1-2с на ввод текста.

### ISSUE THREAD

**Issue by maks-a** [ReanGD/LearningEnglish#52]
Окно ввода слова часто появляется внезапно и возможно случайное введение неправильного ответа. Как вариант решения проблемы - ввести задержку на ввод данных в 1-2с после появления окна.

**Comment by ReanGD** [comment]
Задержку добавил, ее можно указывать в конфиге, по умолчанию 1 сек.
