### ISSUE TITLE
По Enter если пусто, то неправильно

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#58]
Если слово вообще не знаю нужно нажать "Enter" для неправильного ответа.
Сейчас так нельзя - когда не знаешь слово приходится писать что-нибудь и потом нажимать Enter,

**Comment by ReanGD** [comment]
Я специально делал такое поведение, т.к. случайные нажатия на Enter - доставали.
Если я сделаю, так что например по ctrl+Enter пустое поле будет засчитываться за неправильный ответ, такое поведение устроит?

**Comment by maxirk** [comment]
Хм, у меня нет случайных вроде. Я по enter хочу, может подскажете где в коде самому назначить кнопку можно?

**Comment by ReanGD** [comment]
Ок, после работы найду вам строчку, которую нужно закомментировать для этого.

**Comment by ReanGD** [comment]
Достаточно за комментировать вот эту [строчку](https://github.com/ReanGD/LearningEnglish/blob/master/GUI.py#L392) и следующую за ней и все будет работать, как вы хотите.

Если помогло, закройте пожалуйста задачу

**Comment by maxirk** [comment]
Комментировать это поставить перед ней ";"

Поставил 
;if user_answer.strip() == "":
            ;   return

Программа не запускается.

**Comment by ReanGD** [comment]
Нет, комментарий обазначается символов "#"

**Comment by maxirk** [comment]
Ok, получилось. Спасибо! :)

**Comment by maxirk** [comment]
По идее - в настройки бы это вынести

**Comment by ReanGD** [comment]
Ох и не хочется, что бы настройки разрастались. Ну ладно, вынесу в настройку.

**Comment by ReanGD** [comment]
Добавил настройку, называется empty_answer_is_error, если ее выставить в "yes", то пустые ответы будут засчитываться как ошибочные
