### ISSUE TITLE
Выводить цифру кол-ва букв в скобках

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#59]
Надо выводить цифру кол-ва букв в скобках

**Comment by ReanGD** [comment]
Кол-во букв чего, перевода? А в направлении En->Ru может быть несколько вариантов перевода, какое тогда кол-во выводить, и вообще зачем?

**Comment by maxirk** [comment]
Ах, да я забыл что у нас несколько вариантво перевода. Вообщем не нежуно. В других программах так нельзя - отлько одно слово в таблице может быть и поэтому там указывается количество букв. Тут это не нужно.
