### ISSUE TITLE
Убирать из изучения слова со 100% рейтингом и добавлять с 0%

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#60]
Вот я начал учить слова, в статусе изучение 50 слов. Из этих слов по многим я уже достиг 100% в статистике, но программа все равно меня их спрашивает и не включает новые слова на изучение.

Этого не произойдет пока я не достигну для этих 50 слов 100% по всем словам? Но все равно зачем меня спрашивать слова где у меня 100% статистика? 

Допустим я с каким-то словом накосячил - много раз неправильно отвечал и в итоге мне нужно очень много раз ответить правильно, что бы поднять рейтинг до 100% - но при этом я буду каждый раз отвечать и на слова у которых уже 100% рейтинг. Ну это же неправильно!

А в идеале нужно убирать слова со 100% рейтингом из группы в 50 слов (которые в статусе "на изучение") и добавлять новые со статусом 0%.

**Comment by ReanGD** [comment]
Откройте настройки, слово, по умолчанию, считается изученным если у него 97% правильных ответов и как минимум 10 успешных ответов. Как только слово попадает под этот критерий, оно отмечается изученным и его программа начинает спрашивать сильно реже, как минимум в 3 раза (часто более чем в 3 раза, зависит от статистики и еще ряда факторов). На место изученного слова выбирается случайное новое с рейтингом 0%.

Совсем не спрашивать изученные слова - я считаю не правильным, т.к. они имеют свойство забываться, на мой взгляд вполне достаточно того, что они появляются в уроках достаточно редко

> Допустим я с каким-то словом накосячил - много раз неправильно отвечал и в итоге мне нужно очень много раз ответить правильно, что бы поднять рейтинг до 100% - но при этом я буду каждый раз отвечать и на слова у которых уже 100% рейтинг. Ну это же неправильно!

Согласен, только вас уже опередили и предложили другую систему учета ответов: https://github.com/ReanGD/LearningEnglish/issues/50 - почитайте, думаю вам понравиться.

**Comment by maxirk** [comment]
> по умолчанию, считается изученным если у него 97% правильных ответов и как минимум 10 успешных ответов.

Теперь понятно почему она меня мучает :) А где можно количество успешных ответов указать. Я хочу 5 - а то уже 2ую неделю новые слова не добавляются - для меня кажется это сильно много.

**Comment by ReanGD** [comment]
Откройте config.json, там все настройки, что вас интересуют с комментариями.
