### ISSUE TITLE
Возможность задавать синоними английских слов через запятую

### ISSUE THREAD

**Issue by ReanGD** [ReanGD/LearningEnglish#62]

**Comment by maxirk** [comment]
А можно подробнее что это? Наверное как раз что я тут https://github.com/ReanGD/LearningEnglish/issues/66 имаю ввиду?

**Comment by ReanGD** [comment]
Нет, это другое.
Сейчас можно жестко задать только одно английское слово - а в переводе к нему указывать несколько синонимов переводов через запятую, уточняющие фразы и т.п. Попросили нечто подобное сделать и для английских слов.

**Comment by ReanGD** [comment]
Реализовано, правда следует обратить внимание, что статистика и словарь связаны между собой по английскому варианту слова, так что изменив последний, желательно поправить его в файле со статистикой(statistic.json), иначе вы начнете изучать это слово заново.
В рамках задачи #66 я добавлю возможность менять английский вариант слова с автоматическим обновлением статистики.
