### ISSUE TITLE
Добавление вариантов перевода из неправильного ответа.

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#66]
Допустим я ввел правильный перевод и я точно это знаю, но в таблице слов такого ответа нет.
Нажимаю сочетание клавишь на клавиатуре и это слово добавляется в словарь.

Это будет удобно. На данный момент приходится вручную открывать словарь, искать это слово и добавлять - жутко неудобно. Но нужно. Не знакю как вам а мне в процессе упражнения, часто хочется поправить перевод слов в словаре, но т.к. это неудобно не делаю этого. А можно сделать удобно.

**Comment by ReanGD** [comment]
Согласен, возможность редактирования перевода и транскрипции у текущего слова была бы не лишней.
Правда после этого весь словарь будет переформатирован по другому, если это кому-то важно...
Список того, что я буду делать в следующей версии я уже определил, это в будующие доработки.

**Comment by maxirk** [comment]
> Правда после этого весь словарь будет переформатирован по другому, если это кому-то важно...

Не понял что имеете ввиду. ормат словаря disct.json будет другой? Ну это без разницы.

**Comment by ReanGD** [comment]
формат останется такой же - выравнивание съедет

**Comment by maxirk** [comment]
Причем это все-таки должна быть не кнопка в окне. А сочетание клавишь - т.е. что бы с клавиатуры это слово добавлялось. Так не придется руку на мышь отрывать от клавиатуры.

**Comment by ReanGD** [comment]
Кнопка все же нужна, иначе никто просто не узнает, что такая функциональность есть. То что можно продублировать это горячими клавишами - согласен.

**Comment by ReanGD** [comment]
Добавил интерфейс для редактирования слова, умеет автоматически изменять статистику по этому слову, если изменился английский перевод. Редактирование доступно из основного окна (кнопкой или по ctrl+Enter) после того, как вы ответили на слово, а так же из таблицы со статистикой по двойному клику.

**Comment by maxirk** [comment]
1. Я ввел слово неправильно, но я точно знаю, что оно правильно. Нажимаю Ctrl+Enter и вписываю это слово. 
   Но ошибка-то в статистики осталась, это неправильно - хотя непонятно как сделать по-другому.
2. А можно убрать "Подтверждение"? Так-то если я ввел слово - то точно не ошибся. :) Что где закоментить?

**Comment by ReanGD** [comment]
1) Могу посоветовать редактировать словарь до того, как начнете по нему что-то учить :)
Если серьезно, то не так уж критичен один неправильный ответ, тем более с новой системой рейтинга.

2) Диалог с подтверждением я убирать не буду, т.к. действие довольно обширное и много чего меняет, но если хочется - вот эту строчку нужно закомментировать: https://github.com/ReanGD/LearningEnglish/blob/master/GUI.py#L120
На всякий случай, вот текст строчки: if tkMessageBox.askyesno(_("win_confirm_title"), _("msg_confirm_rename"))
