### ISSUE TITLE
Иногда вылетает

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#67]
Иногда вылетает на разных словах.

Ввожу ответ. Поле ввода становится серым. Продолжаю несколько раз жать Enter и программа вылетает. 

Отследить какую-то зависимость не могу.

**Comment by ReanGD** [comment]
Ни разу не наблюдал подобного и повторить не могу. Если получится добиться хоть какой-то стабильности в воспроизведении, пишите, поправлю.
