### ISSUE TITLE
Интерфейс-Лайт (без строки ввода)

### ISSUE THREAD

**Issue by fsergey** [ReanGD/LearningEnglish#68]
Спасибо автору за программу.
Далее предложения.
Предистория: в свое время заучивал английские слова по еще по бумажным карточкам. На одной стороне английские слова на другой перевод. Перекладываешь карточки если помнишь (занимает около 1 сек) и смотришь перевод если не помнишь/сомневаешься (около 3 сек). Понравился этот метод 
1.за быстроту заучивания (можно за 10 минут повторить несколько раз пачку из 100 слов) 
2.т.к. вырабатывается автоматизм во вспоминании перевода. Не разбирался с психологией метода, но на практике перевод всплывает в голове за время меньше секунда без напряжения и долгих ассоциативных цепочек.
<b>Поэтому, имхо, будет небесполезным добавить еще один интерфейс главного окна на котором расположенны только англ.слово(+транскрипция, опция) , кнопка «помню», кнопка «не знаю», кнопка «проверить»</b>
<i>Описание действий кнопок
<b>Помню</b> — отметить слово как «верное» и перейти к другому
<b>Не знаю</b> — отметить как неверное, показать перевод, изменить название на «Следующее слово»,  сделать остальные кнопки не активными
<b>Следующее слово</b> — показать следующее слово , изменить свое название на «Не знаю», сделать все кнопки активными
<b>Проверить</b> — Вызвать диалог со строкой ввода для проверки перевода. По итогам выполнения диалога отметить слово в базе и показать результат.</i>
Этим увеличится скорость повторения слов.

Еще можно продумать работу с выборками слов. Например, есть партия слов, которые мы активно заучиваем в настоящее время. Есть несколько партий, которые мы уже изучили, но их нужно повторить. Есть слова, которые нам упорно не даются (постоянно забываются), их нужно запоминать отдельно и не спеша.

**Comment by ReanGD** [comment]
Я в основном делал под себя, у меня таким образом не получалось запоминать слова, а через написание гораздо лучше идет.

Посмотрите для этого - [Anki](http://ankisrs.net/) обзор на [youtube](http://www.youtube.com/watch?v=UHGWre0Nq4g). Там, как я понял как раз такая система и используется, если чем-то не устроит пишите, учту ошибки Anki и добавлю эту задачу в список на реализацию, но я не знаю когда у меня руки дойдут это все сделать, а найти кого-нибудь для паралельно разработки не удается (

**Comment by maks-a** [comment]
я бы посоветовал @ReanGD не разрываться, на всех не угодишь, делайте в первую очередь для себя и только самое необходимое. запросы от пользователей реализовывать в первую очередь те, которые вписываются в ваши представления о программе.

для пользователей же я бы посоветовал попробовать свои силы в программировании, питон очень быстро учится, свой вариант программы, которая подходит мне больше чем все другие я написал за месяц в свободное от работы время с учетом изучения питона.
