### ISSUE TITLE
Перенос наработок от Maks-a в основной проект

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#69]
https://github.com/maks-a/LearnEnglishWords

Скриншот http://clip2net.com/s/2vmpO
1. Реализован  уход от "накопительной" системы рейтинга к "текущей"
   https://github.com/ReanGD/LearningEnglish/issues/50
2. Вопрос перед стартом урока. (Мне это не нужно. В файле настроек должно отключаться.)
3. Добавлен прогрессбар в главном окне
4. Файловая структура программы упорядочена
5. По-умолчанию в архиве лежит скрипт импорта слов из Lingualeo

Может быть есть что-то еще. Нужно добавить это в основной проект от ReanGD и делать Next Release.

**Comment by ReanGD** [comment]
Да, я видел, спасибо. Там не возможно просто скопировать пару файлов, это очень сильно переделанный проект, но некоторые особенности, я хочу честно скопировать, если автор не против, конечно.

**Comment by maks-a** [comment]
мой проект сильно переделан потому что писался с нуля с подглядыванием на вариант @ReanGD, а не изменением уже готового.
я в другой ветке уже сказал что не против копирования, берите что нравится :)
по поводу вопроса перед стартом урока он нужен по двум причинам:
- переключить раскладку клавиатуры в нужную для урока
- исключить неожиданное выскакивание на экран слов (а то может в уроке быть ненормативная лексика или странные части тела, а в это время вы сотруднику показываете на своем мониторе что-то и тут БАЦ! мошонка!) :)

**Comment by maxirk** [comment]
Ждем, ждем...

**Comment by ReanGD** [comment]
@maxirk, а я думал вы перешли к "конкурентам" :)
Может стоит тогда не ждать, а включиться и помочь?

**Comment by maxirk** [comment]
Я не программист совсем. Все что нужно это скопировать технологию системы рейтинга. А остальные улучшения не так критичны..

**Comment by maxirk** [comment]
Ничего новенького? :)

**Comment by ReanGD** [comment]
Ничего, мне пока не до проекта.

**Comment by ReanGD** [comment]
Всё что хотелось перенести из того проекта - я перенес. Так что закрываю.
