### ISSUE TITLE
добавить часть речи к переводимому слову

### ISSUE THREAD

**Issue by yudjin87** [ReanGD/LearningEnglish#71]
Очень поможет, потому как бывают такие случаи:
last (adj/прилагательное) - последний
но
last (v/глагол) - длиться

**Comment by ReanGD** [comment]
А ни кто и не мешает сейчас добавлять части речи, я как раз недавно сделал доработку, когда к любому английскому слову можно, как и к русскому добавлять уточнения в круглых скобках (лучше через интерфейс, если уже начали изучать, что бы не сбросить статистику по изменяемому слову).
Если имелось ввиду делать это автоматически - то боюсь это не возможно, только вручную, только хардкор )

**Comment by yudjin87** [comment]
ну тогда можно закрывать
