### ISSUE TITLE
Звук

### ISSUE THREAD

**Issue by maks-a** [ReanGD/LearningEnglish#72]
Не знаю как на гитхабе отправить личное сообщение, поэтому написал тут.
На досуге решил подтянуть неправильные глаголы и вот что из этого получилось - https://github.com/maks-a/IrregularVerbs
Самое главное - добавил озвучивание слов, сделал это через pyAudio, может можно как-то по другому, но у меня ушла куча времени на проверку разных вариантов, а заработал только этот. Проверял только под убунтой.
В общем, если найдете что-то полезное для себя - пользуйте на здоровье.

**Comment by maks-a** [comment]
Буду эту ветку в качестве сообщений не по теме использовать.
Не могу на хабре комментировать, т.к. read-only, но увидел у вас коммент http://habrahabr.ru/post/152831/#comment_5197659
Есть уже готовые скрипты, вот девушка на хабре целую статью написала по частотному анализу - http://habrahabr.ru/post/161073/
Я тоже для себя писал простой стеммер, который работал по эталонному словарю на 100к слов, мне этой точности было вполне достаточно.

**Comment by ReanGD** [comment]
Предлагаю использовать ReanGD@yandex.ru в качестве личных сообщений (я правда завтра уезжаю на неделю и не уверен что смогу отвечать сразу, но все же... Так же я не против перейти на ты, если нет возражений :)

Насчет звука - не смущает, то что pyAudio имеет различные бинарники под разные платформы? Я думал про (http://docs.python.org/2/library/winsound.html и http://docs.python.org/2/library/ossaudiodev.html) они хотя бы нативные, правда не знаю какие форматы там поддерживаются. Хотя с другой стороны, если отказаться от кроссплатформенности или хотя бы от OS X, и разрешить себе внешние зависимости от других библиотек - станет сильно проще...

А зачем для неправильных глаголов отдельное приложение, не проще все в одном?

> Есть уже готовые скрипты, вот девушка на хабре целую статью написала по частотному анализу

Да я читал, спасибо, но что-то блин плохо изучается все это дело, не уверен, что в ближайшее время понадобиться кардинально расширять словарь.

**Comment by maks-a** [comment]
По поводу звука: да, хотелось бы конечно кроссплатформенное решение и попроще, но у меня так и не получилось запустить ossaudiodev. я уже в какой-то момент подумал бросить эту затею, но тут удалось запустить pyaudio.

> А зачем для неправильных глаголов отдельное приложение, не проще все в одном?

так получилось, не хотел ломать предыдущую версию, поэтому начал в отдельной папке.
