### ISSUE TITLE
Новый пост на habrahabr.ru

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#73]
Появилось много новых фишек. Думаю сейчас изменений достаточно для нового поста на habrahabr.ru - будет больше пользователей.

Нужно написать о:
- Переходе от накопительной системы к текущей https://github.com/ReanGD/LearningEnglish/issues/50
- Возможности редактировать слова "на лету" https://github.com/ReanGD/LearningEnglish/issues/62 https://github.com/ReanGD/LearningEnglish/issues/66
- Возможности импорта из словаря Lingualeo при помощи скрипта (от Maks-a) https://github.com/ReanGD/LearningEnglish/issues/55

О планах:
- Картинки https://github.com/ReanGD/LearningEnglish/issues/57
- Звуки https://github.com/ReanGD/LearningEnglish/issues/72

ну и т.п.

**Comment by ReanGD** [comment]
Мне лень писать, если честно, тем более, что не так уж и много чего поменялось.
