### ISSUE TITLE
Игнорировать опечатки в ответе

### ISSUE THREAD

**Issue by ReanGD** [ReanGD/LearningEnglish#75]
Появилась идея, не знаю будет ли кому-то полезна:
Игнорировать опечатки при ответе, допустим в русском языке можно "прощать" неправильное написание "ться/тся", удвоенное "н" и т.п. ошибки, которые на смысл слова не влияют, в конце концов  изучается ведь английский язык, а не правописание в русском.
А так же в обоих языках "прощать" ошибки набора - пропущенную букву например.

Если есть мысли по этому поводу, высказывайтесь пожалуйста

**Comment by AntonZelinsky** [comment]
Нужно считать при 80% совпадении(-1-3 символа), как правильное слово. У меня с букву "ё" не приняла, так как в базе была ошибочно поставлена "е" - "желтый".

**Comment by ReanGD** [comment]
Насчет е/ё:
А не подскажите как воспроизвести? Я сейчас для чистоты эксперемента скачал "чистую" последнюю версию https://github.com/ReanGD/LearningEnglish/archive/master.zip на Win7
Убрал из словаря все кроме "желтый" и запустил, принимает ответы и "желтый" и "жёлтый" как правильные.
