### ISSUE TITLE
убрать окно терминала в запущенном состоянии

### ISSUE THREAD

**Issue by AntonZelinsky** [ReanGD/LearningEnglish#79]
Раз уж распространяете в виде исходников, то нужно убрать окно терминала. Очень раздражает, когда лишнее и совсем не нужное для конечного пользователя окно, занимает какую-то часть экрана.

**Comment by ReanGD** [comment]
А как вы запускаете? Вроде нет никаких проблем с консолью:
Я способы запуска описывал в https://github.com/ReanGD/LearningEnglish/wiki/Установка-и-запуск

На Windows можно сделать вот такой bat-ник:
C:\Soft\Python26\pythonw.exe e:\Projects\GIT\LearningEnglish\main.py
естественно со своими путями, все запускается без консоли.
Ну в автозагрузку добавить потом его проблем думаю не возникнет.

На Linux (я пробовал на Ubuntu другого дистрибутива под рукой нет):
Даем права на выполнение:
chmod +x main.py

И потом допустим из mc запускается по enter'у без консоли.
Ну или добавляем в автозагрузку:
Приложения\Системные утилиты\Параметры\Автоматически запускаемые приложения
и добавляем команду: /home/rean/Downloads/Shared/main.py (тоже со своим путем)
при перезагрузке все запускается без консоли.

Как нормально добавить все в автозагрузку в Mac OS - я не знаю, но надеюсь раз в Ubuntu проблем нет, то и тут не будет.

**Comment by AntonZelinsky** [comment]
В Windows 7, двойным щелчком по main.py файлу. В системе стоит Python версии 2.6 и 3.2. А заставлять пользователя писать что-либо в консоле это опять же неправильно. Если бы мне пришлось так запускать приложение, хотя бы больше двух раз, то на третий раз я не стал бы ничего прописывать в консоле, а просто забил на эту программу.

**Comment by ReanGD** [comment]
Да я понимаю, что неудобно, но к сожалению на чистом python проблемно сделать по другому, причем кроссплатформенно. Но в конце концов я же за это не деньги беру, а сделал "под себя" и поделился с окружающими.
Если лень что-то прописывать в консоли - на Windows можно проще: правой кнопкой на main.py выбрать "открыть с помощью"/"выбрать программу"/"обзор" и указать путь к pythonw.exe в папке с python - этот exeшник открывает скрипты без консоли. Там же где-то есть галочка, что бы винда запомнила этот выбор и всегда использовала.

**Comment by AntonZelinsky** [comment]
Так, а зачем в консоле вообще что-либо писать? Ведь если нормально был установлен python, то проблем с обычным запуском(двойной щелчёк по main файлу) не должно быть, он запускается так же как и exe файл.

**Comment by ReanGD** [comment]
Проблемы начинаются если это не windows или если стоит несколько версий python. Но наверное вы правы, лучше переименовать main.py в main.pyw, хуже не станет. Переименовал в основной ветке.

**Comment by AntonZelinsky** [comment]
у меня 2.6 и 3.2 стоят. проблем нет

**Comment by ReanGD** [comment]
Вам вероятно повезло и pyw файлы привязаны именно к 2.6
Если бы было наоборот, то скрипт скорее всего бы упал, т.к. с переходом на 3 версию python уж очень сильно изменился.
