### ISSUE TITLE
Ошибка (по крайней мере у меня)

### ISSUE THREAD

**Issue by arsaaa** [ReanGD/LearningEnglish#81]
Я немного модифицировал ваш код и ошибся в файле dictionary.py, но когда программа интепретировалась, т.к. в строке 75 в файле есть:
except dictionary.ErrDict as err:
но говорит, что не глоб. переменной по имени dictionary. Так что мне кажется надо добавить
import dictionary
ну или по-другому, не мне вас учить
По крайней мере у меня прокатило

**Comment by ReanGD** [comment]
Я как понял вы про файл src/edit_word_dialog.py. Да я там действительно забыл импортировать модуль.
Поправил. Спасибо большое.
