### ISSUE TITLE
Не дает ввести правильное слово на русском

### ISSUE THREAD

**Issue by vozbu** [ReanGD/LearningEnglish#84]
Проблема в такой конфигурации:
my_dict.json:

``` json
[
    [
        "hijacking",
        "угон (самолета, судна, автомобиля), кража (из автомобиля)"
    ]
]
```

Запускаю с этим словарем, выдает мне слово на английском ("hijacking"), ввожу на русском "угон", нажимаю Enter, ничего не происходит, только ошибки в консоли, причем если Enter еще нажать, ошибка повторяется. И при любом тексте. Т.е. можно только урок завершить и ждать следующего. Ошибки такие:

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1410, in **call**
>     return self.func(*args)
>   File "/home/vozbu/programming/LearningEnglish/src/GUI.py", line 203, in on_return
>     self.end_practice(user_answer)
>   File "/home/vozbu/programming/LearningEnglish/src/app.py", line 64, in end_practice
>     is_success, right_answer = self.practice.check(user_answer)
>   File "/home/vozbu/programming/LearningEnglish/src/lesson.py", line 35, in check
>     is_success, right_answer = self.word.check(user_answer, self.type_pr)
>   File "/home/vozbu/programming/LearningEnglish/src/word.py", line 125, in check
>     is_success = self._check_ru(answer)
>   File "/home/vozbu/programming/LearningEnglish/src/word.py", line 112, in _check_ru
>     if re.match(it + "\Z", answer) is not None:
>   File "/usr/lib64/python2.7/re.py", line 137, in match
>     return _compile(pattern, flags).match(string)
>   File "/usr/lib64/python2.7/re.py", line 242, in _compile
>     raise error, v # invalid expression
> error: unbalanced parenthesis

Возможно я не могу указывать в скобках запятые, т.к. они служат разделителями слов, но тем не менее поведение программы неожиданное.

**Comment by ReanGD** [comment]
Да действительно дело было в запятых, поправил. Спасибо за подробной баг-репорт
