### ISSUE TITLE
Перевести текущее слово в Yandex Словаре

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#85]
Сделать кнопочку "Перевести текущее слово в Yandex Словаре".
Когда кликаю по этой кнопке, в браузере открывается страница перевод текущего слова (то которое спрашивают перевод). Хотя еще удобнее было бы что бы ниже программы появлялся фрейм (но это наверно сложновато будет сделать).

Теоретически это можно сделать.
Программа должна "брать" текущее слово и подставлять ее в урл http://slovari.yandex.ru/СЛОВО/en/#lingvo/ и "выполнить"

Это часто нужно, когда думаешь, что знаешь перевод слова и хочешь отредактировать его, но не уверен. Сейчас я вручную каждый раз лажу в словарь. А так бы было бы намного удобнее.

Кроме того, интересно посмотреть какие еще значения у него есть.

**Comment by ReanGD** [comment]
О, вы вернулись, вовремя, а то я что-то забросил проект.
Выглядит разумно, попробую сделать

**Comment by ReanGD** [comment]
Сделал. Рядом с кнопкой редактирования слова появилась кнопка поиска слова в интернете. В конфиге добавил настройку internet_dictionary_url где можно задать шаблон для поиска слова, по умолчанию настроено на yandex словари.
