### ISSUE TITLE
Знаю/не знаю вместо написания

### ISSUE THREAD

**Issue by maxirk** [ReanGD/LearningEnglish#86]
Что-то как-то устал слова печатать. Теперь хочется просто быстро "протыкивать" слова - на "знаю" / "не знаю". А вы не думали поменять / добавить упражнение?

Самому не надоело печатать?

Показывается слово c кнопкой "Показать ответ". Нажимаю, появляется перевод и 2 кнопки "Знаю" (нажатие увеличивает %) "Не знаю" (нажатие уменьшает %).

Сейчас пробую Anki (какая-то сильно навороченная программа), но там мне не очень понятно как работает система - когда какие карточки всплывают.

**Comment by ReanGD** [comment]
Нет, пока не надоело, одна из основных целей - научиться письменной речи. И я не планирую делать ничего подобного, по крайней мере в обозримом будущем.

**Comment by maxirk** [comment]
> И я не планирую делать ничего подобного, по крайней мере в обозримом будущем.

А теоретически можно это сделать? Т.е. если кто-нибудь другой попробует (например я изучу питон :))

**Comment by ReanGD** [comment]
Да конечно, в принципе это не так сложно. Азы python можно освоить за выходные, если раньше программировали, а дальше делать форк проекта и можно экспериментировать. Полностью заменить текущие упражнения с вводом ответов на "знаю/не знаю" даже с учетом того, что придется разбираться в проекте - дело нескольких дней, не больше.

**Comment by maxirk** [comment]
> Азы python можно освоить за выходные, если раньше программировали.

Вот только я никогда не программировал :)

**Comment by ReanGD** [comment]
> Вот только я никогда не программировал :)

У меня, к сожалению, тоже нет ни времени, ни желания делать ненужную мне функциональность и отлаживать ее в трех разных операционках, писать тесты, придумывать как это должно согласовываться с предыдущими режимами уроков и т.п.
