### ISSUE TITLE
Какая лицензия у данного проекта?

### ISSUE THREAD

**Issue by pukkutukkutabu** [ReanGD/LearningEnglish#88]
Хотел бы узнать лицензию данного проекта.

**Comment by ReanGD** [comment]
Добавил лицензию "Apache License Version 2.0"
Вы планируете что-то добавить в программу?

**Comment by pukkutukkutabu** [comment]
Ну вообще я уже добавил из серии "для себя". 
В свое время начинал писать программу типа вашей и импортер из лингуалео. Потом увидел вашу программу и с тех пор ей и пользуюсь. Лично для своего удобства добавил показ картинок и проигрывание одноименной озвучки, импортированных скриптами с лингуалео.
Спросил про лицензию так как возможно думал над форком проекта, либо коммитить сюда с позволения автора, но я так понял что мои взгляды немного отличаются. Я изначально сижу на линуксе, поэтому мои коммиты бы поломали кроссплатформенность. Например озвучка идет у меня через mplayer. Под Win находил тоже консольный проигрыватель mp3, но в связи с лицензией его никуда не впихнешь, mplayer для windows был весьма печален, а проигрывание аудио с помощью питона - это полное ломание кроссплатформенности (хотя лукавлю, слышал про pyglet, но руки так и не дошли).
Вообщем при наличии времени тоже бы хотел внести посильный вклад в программу
