### ISSUE TITLE
При ручном изменении слов в словаре, программа отказывается запускаться

### ISSUE THREAD

**Issue by nIhutiv** [ReanGD/LearningEnglish#90]
Суть проблемы в том, что, не пойму конечно по какой причине, при внесении изменений в ручную в dict и его сохранении перестает открываться main. При том помню, что ранее, еще на заре программы, не было такой проблемы. Есть мысли о неправильном форматировании текста, об ошибочном сохранении с другой кодировкой. Но все эти вещи перепробовал, изменял и ничего.
Боюсь, конечно, что проект завис, но меня он устраивает во всем. К нему привык. И сейчас как будто что-то убрали из повседневного распорядка.

**Comment by ReanGD** [comment]
Спасибо за отзыв.
Пришлите мне на почту(reangd (собака) yandex.ru) пример словаря, который приводит к зависанию, я постараюсь на выходных выяснить в чем дело.

**Comment by ReanGD** [comment]
У вас в словах "Trip operations" и "Equivalent circulating density, ECD" в переводе используется перенос строки, уберите его и все заработает. Если помогло, закройте пожалуйста эту задачу.

**Comment by nIhutiv** [comment]
Спасибо! Все действительно было в форматировании! Исправил
