### ISSUE TITLE
Поддержка японского языка

### ISSUE THREAD

**Issue by MetalheadSanya** [ReanGD/LearningEnglish#91]
В общем, немного не по теме, но почему бы и нет.
Столкнулся со следующей проблемой, в тестовом поле, на OS X 10.11, не могу вводить символы хираганой. При копировании из другого места и вставке программа определяет все правильно.

Я конечно попробовал сам найти проблему, но никаких намеков не нашел. google тоже молчит. Может хотя бы подскажите чем gui рисуете?

**Comment by ReanGD** [comment]
Подсказать, я конечно подскажу - [TkInter](https://wiki.python.org/moin/TkInter), проблема скорее всего в том, что текущие шрифты [вот тут и ниже](https://github.com/ReanGD/LearningEnglish/blob/master/src/GUI.py#L37) не поддерживают японский и их нужно будет заменить на другие, [вот тут подробнее](http://forums.devshed.com/python-programming-11/tkinter-japanese-kotaeri-input-method-954173.html). Сам к сожалению проверить не могу, т.к. бесконечно далек от японского и у меня сейчас нет ни OS X, ни нужных шрифтов, ни японской раскладки

**Comment by MetalheadSanya** [comment]
Проблема не в шрифте, т.к. в Label он выводится и выводится корректно.
Как я почитал вашу ссылку, на OS X TkInter поддерживал японский, но поддержку поломали (предпоследнее сообщение). В общем печально, думаю issue можно закрывать.

**Comment by ReanGD** [comment]
Тогда, ничем помочь не смогу. Закрываю
